theme: jekyll-theme-cayman
description: A variety of data science and coding projects
author: Vince Gregoric
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
